config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'posts/index'
  
  resources :authors
  get 'authors/index'
  
  resources :sessions
  get 'sessions/new'

  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates_presence_of :name, :password, :password_confirmation, :email, :security_question, :security_answer
  validates_confirmation_of :password
  
  before_save :encrypt
  
  def self.authenticate name, password
    @author = find_by_name(name)
	
	if @author && @author.password == BCrypt::Engine.hash_secret(password, @author.password_salt)
	  return @author
	end
	return false
  end
  
  def encrypt
	if password.present?
	  self.password_salt = BCrypt::Engine.generate_salt
	  self.password = BCrypt::Engine.hash_secret(password, password_salt)
	
	  self.security_salt = BCrypt::Engine.generate_salt
	  self.security_answer = BCrypt::Engine.hash_secret(security_answer, security_salt)
	end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "header"
  
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
#@author Grant Gadomski

class AuthorsController < ApplicationController
  def index
	#Lists all of the authors to choose from.
	@authors = Author.all
  end
  
  def show
    #Lists all of the posts by author, given the author's id as a param.
	@posts = Post.where(:author => params[:author])
  end
  
  def new
	#Corresponds to the view that displays the form to create a new author.
  end
  
  def create
	#Creates a new author in the database.
	if require_login
	  @author = Author.new(author_params)
	
	  if (@author.save)
	    session[:author] = @author.name
	    redirect_to @author
	  else
	    redirect_to root_path
	  end
	  
	else
	  #redirect_to root_path
    end
  end
  
  private
    def author_params
	  #Checks the information entered to ensure it's what's required for a new author.
	  params.require(:author).permit(:name, :password, :password_confirmation, :email, :security_question, :security_answer)
	end
	
	def require_login
	  #Ensures that an author is currently logged in.
	  if session[:author]
	    return true
	  else
	    return false
	  end
	end
end

app/controllers/posts_controller.rb
#@author Grant Gadomski

class PostsController < ApplicationController
  def index
	#Homepage for the application, displays all posts in the database from newest to oldest.
    @posts = Post.all
  end
  
  def new
	#Coresponds to the view containing the form for a new post.
  end
  
  def create
    #Saves a new post to the database.
	if require_login
      @post = Post.new(post_params)
	  @post.save
	  redirect_to @post
	else
	  redirect_to root_path
	end
  end
  
  def show
	#Shows all of a specific post.
	@post = Post.find(params[:id])
  end
  
  private
	def post_params
	  #Checks new post to ensure it fills all criteria before saving it to the database.
	  params.require(:post).permit(:title, :author, :date, :content)
	end
	
	def require_login
	  #Ensures that an author is currently logged in.
	  if session[:author]
	    return true
	  else
	    return false
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    puts(params[:password])
	
    @author = Author.authenticate params[:name], params[:password]
	if @author
	  session[:author] = @author.name
	  redirect_to @author
	else
	  redirect_to root_path
	end
  end
  
  def destroy
    session[:author] = nil
	redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/authors/index.html.erb
<% if (@authors.blank?) %>
	<h2>Sorry brah, no one writes here these days.</h2>
<% else %>
	<% @authors.each do |author| %>
		<h2><%= link_to(author.name, "/authors/show?author=" + author.name) %></h2>
	<% end %>
<% end %>

app/views/authors/new.html.erb
<%= form_for :author, url: authors_path do |form| %>
	<p>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</p>
	
	<p>
		<%= form.label :password %>
		<%= form.password_field :password %>
	</p>
	
	<p>
		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation %>
	</p>
	
	<p>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</p>
	
	<p>
		<%= form.label :security_question %>
		<%= form.text_field :security_question %>
	</p>
	
	<p>
		<%= form.label :security_answer %>
		<%= form.text_field :security_answer %>
	</p>
	
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/authors/show.html.erb
<% if (@posts.blank?) %>
	<h2>Sorry brah, no posts seem to be here.</h2>
<% else %>
	<% @posts.each do |post| %>
		<p>
			<h3><%= post.title %></h3></br>
			<%= post.updated_at.strftime("%m/%d/%Y") %></br>
			<p><%= post.content %></p>
		</p>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MattyVandtheG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8" />    
		<title></title> <!--Replace with something to take the title of the current post, or the current page (Home, Authors, etc.).-->
		<link href="bootstrap.css" type="text/css" rel="stylesheet" />
		<link href="a_dumb_comedy_site.css" type="text/css" rel="stylesheet" />
		<style>
			#title {
				margin-left: auto;
				margin-right: auto;
				color: white;
				margin-top: 10px;
				display: inline;
				text-decoration: none;
				font-family: "Times", serif;
				font-style: oblique;
			}

			#tagline {
				margin-left: 270px;
				color: white;
				margin-top: 10px;
				display: inline;
				font-family: "Comic Sans MS", cursive, sans-serif;
				margin-bottom: 5px;
			}

			#first_link {
				margin-left: 30px;
				margin-top: 10px;
				display: inline;
				color: white;
				text-align: right;
				margin-bottom: 5px;
			}

			#second_link {
				margin-left: 10px;
				margin-top: 10px;
				display: inline;
				color: white;
				text-align: right;
				margin-bottom: 5px;
			}
		</style>
	</head>

	<body>
		<form id="form1" runat="server">
			<div id="site">
				<div class="navbar">
					<div class="navbar-inner" style="background-color:#00a1f1">
						<div class="row">
							<h3 id="title"><%= link_to('Matty V and the G', '/posts/') %></h3>
							<h5 id="tagline">Now with more Comic Sans!</h5>
							<span id="first_link"><%= link_to('Authors', '/authors/') %></span>
						</div>
					</div>
				</div>
			</div>
		</form>
		<%= yield %>
	</body>
</html>

app/views/posts/index.html.erb
<% if (@posts.blank?) %>
	<h2>Sorry brah, no posts seem to be here.</h2>
<% else %>
	<% @posts.each do |post| %>
		<p>
			<h3><%= post.title %></h3></br>
			<%= link_to(post.author, '/authors/show?author=' + post.author) %></br>
			<%= post.updated_at.strftime("%m/%d/%Y") %></br>
			<p><%= post.content %></p>
		</p>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
	<p>
		<%= f.label :title %></br>
		<%= f.text_field :title %>
	</p>
	
	<!--As user functionality is added, the author field will be replaced with checking who's logged in.
		However it's here currently for testing purposes.-->
	<p>
		<%= f.label :author %></br>
		<%= f.text_field :author %>
	</p>
		
	<p>
		<%= f.label :content %></br>
		<%= f.text_area :content %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/show.html.erb
<p>
	<h4 style="display: inline;">Title: </h4><%= @post.title %></br>
	<h4 style="display: inline;">Author: </h4><%= link_to(@post.author, '/authors/show?author=' + @post.author) %></br>
	<h4 style="display: inline;">Date: </h4><%= @post.updated_at.strftime("%m/%d/%Y") %>
</p>

<p>
	<%= @post.content %>
</p>